name: Social security number on Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore and build
        run: |
            dotnet restore
            dotnet build
            
      - name: Social security number
        run: dotnet test


      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build


      - name: Login in dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      
      - name: build and push docker image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/Calc .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/Calc

